# Generated by Django 3.2 on 2021-04-24 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=800)),
                ('answer', models.TextField()),
            ],
            options={
                'db_table': 'faqs',
            },
        ),
    ]
