# Generated by Django 3.2.8 on 2021-10-23 16:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('duration', models.IntegerField(default=30)),
                ('price', models.FloatField(default=0)),
                ('downloads', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'keys',
            },
        ),
    ]
