# Generated by Django 3.2.8 on 2021-10-26 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_alter_subscription_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
