# Generated by Django 3.2.8 on 2021-10-26 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_alter_subscription_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='description',
        ),
    ]
