# Generated by Django 3.2 on 2021-09-19 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tos',
            table='terms_of_service',
        ),
    ]
