# Generated by Django 3.2.8 on 2021-10-26 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_alter_subscription_table'),
        ('invoice', '0002_auto_20211023_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='subscription',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='subscription.subscription'),
        ),
    ]
